name: NodeJS with Webpack
permissions:
  id-token: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: npm install

    - name: NPM Test
      run: npm test

    - name: Webpack Build
      run: npm run build

    - name: Upload a Build Artifact
      if: github.event.pull_request.merged == true
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: dist
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 7

    - name: Deploy GitHub Pages site
      if: github.event.pull_request.merged == true
      uses: actions/deploy-pages@v1.0.10
      with:
        # Should this action only emit build telemetry instead of deploying the build artifact?
        #emit_telemetry: # optional, default is false
        # GitHub token
        #token: # default is ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        #timeout: # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        #error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        #reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: dist
